version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.0

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --if-missing --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test